line-length = 100
target-version = "py310"

[lint]
ignore = [
  "E501",
  "ANN401",
  "ANN101",
  "ANN102",
  "PLR0913",
  "PLR2004",
  "PLR0917",
  "PLR6301",
  "ANN002",
  "ERA001",
  "RUF100",
  "D100",
  "D104",
  "D105",
  "D107",
]
preview = true
select = [
  "E",
  "W",
  "C90",
  "F",
  "UP",
  "B",
  "SIM",
  "I",
  "N",
  "TCH",
  "ANN",
  "ASYNC",
  "A",
  "C4",
  "EM",
  "FA",
  "ICN",
  "G",
  "PIE",
  "T20",
  "ARG",
  "ERA",
  "LOG",
  "PL",
  "TRY",
  "D",
  "RUF",
]

[lint.per-file-ignores]
"**/__init__.py" = ["F403", "F401"]
"enka/gi.py" = ["F403", "F401"]
"enka/hsr.py" = ["F403", "F401"]
"enka/models/*.py" = ["ALL"]
"examples/**.py" = ["T201", "ERA001"]
"test.py" = ["D", "T201"]
"tests/*.py" = ["D"]

[lint.flake8-type-checking]
quote-annotations = true

[lint.pydocstyle]
convention = "google"
